#!/usr/bin/env python3
"""
Command of the Day Generator for KubeToOps.
Generates command-of-the-day/README.md and updates command-of-the-day/history.json deterministically.
"""
import argparse
import datetime
import json
import os
import sys
from select_command import load_commands, load_history, select_command


def format_safety_badge(safety_level: str) -> str:
    safety_lower = str(safety_level).lower()
    if safety_lower == "safe":
        return "🟢 Safe"
    elif safety_lower == "caution":
        return "🟡 Caution"
    elif safety_lower == "destructive":
        return "🔴 Destructive"
    return f"⚪ {safety_level}"


def render_markdown(cmd: dict, date_str: str) -> str:
    safety_badge = format_safety_badge(cmd.get("safety", "safe"))
    
    breakdown_section = ""
    if cmd.get("breakdown") and isinstance(cmd["breakdown"], list):
        breakdown_section = "\n### Command Breakdown\n\n"
        for item in cmd["breakdown"]:
            flag = item.get("flag", "")
            meaning = item.get("meaning", "")
            breakdown_section += f"- `{flag}`: {meaning}\n"

    example_str = cmd.get("example", cmd.get("command", ""))
    prereqs = cmd.get("prerequisites", "Requires active `kubectl` connection and appropriate cluster permissions.")
    common_mistake = cmd.get("common_mistake", "Running against the wrong namespace or context without checking current-context first.")
    docs_url = cmd.get("official_docs", "https://kubernetes.io/docs/reference/kubectl/")
    verified_str = "Verified ✅" if cmd.get("verified") else "Unverified ⚠️"
    notes = cmd.get("verification_notes", "Tested against Kubernetes local environment.")

    content = f"""<!-- THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY. EDIT content/commands.yaml INSTEAD. -->
# ⚡ Kubernetes Command of the Day ({date_str})

## 📌 {cmd.get('title', 'Featured Command')}

```bash
{cmd.get('command', '')}
```

| Metadata | Details |
| :--- | :--- |
| **Category** | `{cmd.get('category', 'general').capitalize()}` |
| **Difficulty** | `{cmd.get('difficulty', 'intermediate').capitalize()}` |
| **Safety Rating** | **{safety_badge}** |
| **Verification Status** | {verified_str} ({notes}) |

---

### 📖 What It Does

{cmd.get('description', '')}

### 💡 Why It Is Useful

{cmd.get('why', '')}

### 💻 Practical Example

```bash
{example_str}
```
{breakdown_section}
### ⚙️ Prerequisites

{prereqs}

### ⚠️ Common Mistake

{common_mistake}

---

### 📚 Official Documentation

👉 [{cmd.get('title', 'Official Docs')}]({docs_url})
"""
    return content


def update_history_file(history_path: str, cmd: dict, date_str: str):
    history = load_history(history_path)
    
    # Check if entry for date already exists
    updated = False
    for entry in history:
        if entry.get("date") == date_str:
            entry["id"] = cmd.get("id")
            entry["title"] = cmd.get("title")
            updated = True
            break
            
    if not updated:
        history.append({
            "id": cmd.get("id"),
            "date": date_str,
            "title": cmd.get("title")
        })

    os.makedirs(os.path.dirname(os.path.abspath(history_path)), exist_ok=True)
    with open(history_path, "w", encoding="utf-8") as f:
        json.dump(history, f, indent=2)


def main():
    parser = argparse.ArgumentParser(description="Generate Command of the Day Markdown for KubeToOps")
    parser.add_argument("--catalog", default="content/commands.yaml", help="Path to commands.yaml")
    parser.add_argument("--history", default="command-of-the-day/history.json", help="Path to history.json")
    parser.add_argument("--output", default="command-of-the-day/README.md", help="Target markdown file")
    parser.add_argument("--date", default=datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d"), help="Date YYYY-MM-DD")
    parser.add_argument("--command-id", default=None, help="Explicit command ID to generate")
    args = parser.parse_args()

    try:
        catalog = load_commands(args.catalog)
        history = load_history(args.history)
        cmd = select_command(catalog, history, args.date, args.command_id)

        md_content = render_markdown(cmd, args.date)
        os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(md_content)

        update_history_file(args.history, cmd, args.date)
        print(f"Successfully generated {args.output} for command {cmd.get('id')} ({cmd.get('title')})")
    except Exception as e:
        print(f"Error generating Command of the Day: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
